[project]
name = "phag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "James Richmond", email = "jrichmond@sescollc.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.0",
    "pillow>=10.0.0",
    "uvicorn>=0.30.0",
]

[dependency-groups]
dev = [
    "httpx>=0.27.0",
    "pytest>=8.0.0",
]

[project.scripts]
phag = "phag.cli:main"

[build-system]
requires = ["uv_build>=0.11.17,<0.12.0"]
build-backend = "uv_build"
